/* Moteur de rendu, textures, lumières */
/* ================= RENDU ================= */
const renderer=new THREE.WebGLRenderer({canvas:$("gl"),antialias:false,powerPreference:"low-power"});
renderer.setPixelRatio(1);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.BasicShadowMap;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x000000,.02);scene.background=new THREE.Color(0x000000);
const cam=new THREE.PerspectiveCamera(40,1,.1,160);
const snapU={value:new THREE.Vector2(100,60)};
function snap(m){m.onBeforeCompile=s=>{s.uniforms.uSnap=snapU;s.vertexShader="uniform vec2 uSnap;\n"+s.vertexShader.replace("#include <project_vertex>","#include <project_vertex>\n vec4 sp=gl_Position; sp.xyz/=sp.w; sp.xy=floor(sp.xy*uSnap+0.5)/uSnap; gl_Position=vec4(sp.xyz*gl_Position.w,gl_Position.w);");};return m;}
function mkTex(size,draw,rep,h){const c=document.createElement("canvas");c.width=size;c.height=h||size;const x=c.getContext("2d");draw(x,size,h||size);const t=new THREE.CanvasTexture(c);t.magFilter=t.minFilter=THREE.NearestFilter;t.generateMipmaps=false;t.wrapS=t.wrapT=THREE.RepeatWrapping;if(rep)t.repeat.set(rep[0],rep[1]);return t;}
function speckle(x,w,h,n,cols){for(let i=0;i<n;i++){x.fillStyle=rnd(cols);x.fillRect(Math.random()*w|0,Math.random()*h|0,1,1);}}
function hatch(x,w,h,step,a,dir){x.strokeStyle="rgba(0,0,0,"+a+")";x.lineWidth=1;for(let i=-h;i<w+h;i+=step){x.beginPath();x.moveTo(i+.5,0);x.lineTo(i+.5+dir*h,h);x.stroke();}}
const lam=(c,map,o)=>snap(new THREE.MeshLambertMaterial(Object.assign({color:c,map:map||null},o||{})));
const bas=(c,o)=>snap(new THREE.MeshBasicMaterial(Object.assign({color:c},o||{})));
function box(w,h,d,mat,x,y,z,parent,cast){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x||0,y||0,z||0);m.castShadow=!!cast;m.receiveShadow=true;if(parent&&parent===STG)m.userData.st=true;(parent||scene).add(m);return m;}
const texCloth=mkTex(16,(x,w,h)=>{x.fillStyle="#fff";x.fillRect(0,0,w,h);hatch(x,w,h,3,.22,1);speckle(x,w,h,30,["#bbb","#999"]);});
const texSkin=mkTex(16,(x,w,h)=>{x.fillStyle="#fff";x.fillRect(0,0,w,h);hatch(x,w,h,4,.14,-1);});
const texBall=mkTex(32,(x,w,h)=>{x.fillStyle="#8a5e38";x.fillRect(0,0,w,h);speckle(x,w,h,170,["#5a3b22","#9a6e46","#4a2f1a"]);x.fillStyle="#24160c";[0,11,22].forEach(y=>x.fillRect(0,y,w,1));[0,16].forEach(xx=>x.fillRect(xx,0,1,h));x.fillStyle="#e8dcc4";for(let i=1;i<w;i+=3)[0,11,22].forEach(y=>x.fillRect(i,y,1,1));for(let j=1;j<h;j+=3)[0,16].forEach(xx=>x.fillRect(xx,j,1,1));hatch(x,w,h,4,.18,1);});
function stoneTex(base,cols,rep,hA){return mkTex(32,(x,w,h)=>{x.fillStyle=base;x.fillRect(0,0,w,h);speckle(x,w,h,220,cols);x.fillStyle="#000";for(let r=0;r<4;r++){const y=r*8;x.fillRect(0,y,w,1);const off=r%2?8:0;for(let c=off;c<w+16;c+=16)x.fillRect(c%w,y,1,8);}hatch(x,w,h,3,hA||.26,-1);},rep);}
const groundDraw=(base,cols)=>(x,w,h)=>{x.fillStyle=base;x.fillRect(0,0,w,h);speckle(x,w,h,280,cols);hatch(x,w,h,4,.26,1);};
function ironTex(rep){return mkTex(32,(x,w,h)=>{x.fillStyle="#3a3230";x.fillRect(0,0,w,h);speckle(x,w,h,200,["#241e1c","#4a403c","#5a3020"]);x.fillStyle="#000";x.fillRect(0,0,w,1);x.fillRect(0,16,w,1);x.fillRect(0,0,1,h);x.fillRect(16,0,1,h);x.fillStyle="#8a7a70";[[3,3],[13,3],[3,13],[13,13],[19,3],[29,3],[19,19],[29,19],[3,19],[13,29]].forEach(p=>x.fillRect(p[0],p[1],1,1));hatch(x,w,h,3,.2,1);},rep);}
const tileDraw=()=>((x,w,h)=>{x.fillStyle="#625e68";x.fillRect(0,0,w,h);speckle(x,w,h,240,["#4e4a54","#76727c","#58545e","#443f4a"]);x.fillStyle="#1a181e";for(let i=0;i<w;i+=16){x.fillRect(i,0,1,h);x.fillRect(0,i,w,1);}hatch(x,w,h,4,.18,1);});
function glassTex(){return mkTex(32,(x,w,h)=>{const pal=["#6b2a8a","#9a1c14","#2a4a8a","#c08a2a","#2a6a5a","#4a2a6a"];for(let yy=0;yy<h;yy+=4)for(let xx=0;xx<w;xx+=4){x.fillStyle=rnd(pal);x.fillRect(xx,yy,4,4);}x.fillStyle="#0a0808";for(let i=0;i<w;i+=4){x.fillRect(i,0,1,h);x.fillRect(0,i,w,1);}x.fillRect(15,0,2,h);x.fillRect(0,15,w,2);});}
function pitchTex(draw,col){const tc=document.createElement('canvas');tc.width=tc.height=32;draw(tc.getContext('2d'),32,32);return mkTex(352,(x,w,h)=>{x.fillStyle=x.createPattern(tc,'repeat');x.fillRect(0,0,w,h);const cc=document.createElement('canvas');cc.width=w;cc.height=h;const c=cc.getContext('2d');c.strokeStyle=col;c.lineWidth=2;const U=16,cx=176,cy=96,X0=cx-8.2*U,X1=cx+8.2*U,Y0=cy-4.3*U,Y1=cy+4.3*U;c.strokeRect(X0,Y0,X1-X0,Y1-Y0);c.beginPath();c.moveTo(cx,Y0);c.lineTo(cx,Y1);c.stroke();c.beginPath();c.arc(cx,cy,27,0,Math.PI*2);c.stroke();c.strokeRect(X0,cy-35,38,70);c.strokeRect(X1-38,cy-35,38,70);c.strokeRect(X0,cy-21,14,42);c.strokeRect(X1-14,cy-21,14,42);c.fillStyle=col;c.fillRect(cx-2,cy-2,4,4);c.fillRect(X0+26,cy-1,3,3);c.fillRect(X1-29,cy-1,3,3);c.globalCompositeOperation='destination-out';for(let i=0;i<1500;i++)c.fillRect(Math.random()*w|0,Math.random()*h|0,1+(Math.random()*2|0),1);x.drawImage(cc,0,0);x.globalAlpha=.18;x.fillStyle='#000';for(let i=0;i<60;i++){x.beginPath();x.arc(Math.random()*w,Math.random()*h,4+Math.random()*12,0,Math.PI*2);x.fill();}x.globalAlpha=1;},null,192);}
function chalkTexOld(col){return mkTex(256,(x,w,h)=>{x.strokeStyle=col;x.lineWidth=2;x.strokeRect(2,2,w-4,h-4);x.beginPath();x.moveTo(w/2,2);x.lineTo(w/2,h-2);x.stroke();x.beginPath();x.arc(w/2,h/2,17,0,Math.PI*2);x.stroke();x.strokeRect(2,h/2-30,34,60);x.strokeRect(w-36,h/2-30,34,60);x.strokeRect(2,h/2-15,13,30);x.strokeRect(w-15,h/2-15,13,30);x.fillStyle=col;x.fillRect(w/2-2,h/2-2,4,4);x.globalCompositeOperation="destination-out";for(let i=0;i<2600;i++)x.fillRect(Math.random()*w|0,Math.random()*h|0,1+(Math.random()*2|0),1);},null,128);}

/* Lumières */
const amb=new THREE.AmbientLight(0xffffff,.8);scene.add(amb);
const key=new THREE.DirectionalLight(0xffffff,.5);key.castShadow=true;key.shadow.mapSize.set(512,512);Object.assign(key.shadow.camera,{left:-12,right:12,top:10,bottom:-10,near:1,far:50});scene.add(key);scene.add(key.target);
const pts=[0,1,2,3].map(()=>{const l=new THREE.PointLight(0xffffff,0,18,2);scene.add(l);return l;});
let ptBase=[0,0,0,0];
function setEnv(fc,fd,a,k,p){scene.fog.color.setHex(fc);scene.fog.density=fd;scene.background.setHex(fc);amb.color.setHex(a[0]);amb.intensity=a[1];key.color.setHex(k[0]);key.intensity=k[1];key.position.set(k[2],k[3],k[4]);pts.forEach((l,i)=>{const q=p[i];if(q){l.color.setHex(q[0]);l.position.set(q[1],q[2],q[3]);ptBase[i]=q[4];}else{ptBase[i]=0;l.intensity=0;}});}
